version: '3.8'

services:
  db:
    image: postgres
    container_name: nest-postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: gimmingi
      POSTGRES_PASSWORD: alsrl
      POSTGRES_DB: mydb
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
